openapi: 3.0.0
info:
  title: Memeic API
  version: 1.0.0
servers:
  - url: https://jsonplaceholder.typicode.com

tags:
  - name: post
paths:
  /posts:
    get:
      tags:
        - post
      summary: Get all posts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
components:
  schemas:
    Post:
      type: object
      properties:
        userId:
          type: integer
        id:
          type: integer
        title:
          type: string
        body:
          type: string
      required:
        - userId
        - id
        - title
        - body
